packages:
  - apps/*
  - packages/*

allowBuilds:
  "@tailwindcss/oxide": true
  better-sqlite3: true
  esbuild: true
  unrs-resolver: true

catalog:
  "@fastify/cookie": 11.0.2
  "@tailwindcss/vite": 4.3.3
  "@types/better-sqlite3": 7.6.13
  "@types/react": 19.1.9
  "@types/react-dom": 19.1.7
  "@types/sanitize-html": 2.16.0
  "@vitejs/plugin-react": 6.0.4
  ajv: 8.20.0
  ajv-draft-04: 1.0.0
  ajv-formats: 3.0.1
  better-sqlite3: 12.2.0
  canonicalize: 2.1.0
  drizzle-kit: 0.31.4
  drizzle-orm: 0.45.2
  fastify: 5.8.5
  lucide-react: 0.536.0
  react: 19.2.0
  react-dom: 19.2.0
  sanitize-html: 2.17.0
  tailwindcss: 4.3.3
  zod: 4.0.14
